version: '3'
volumes: 
    dados:  
services: 
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD="1234"
        volumes: 
            # Volume de dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    frontend:
        image: nginx:1.13
        volumes: 
            # Site
            - ./web:/usr/share/nginx/html/
            # Configuração do proxy reverso
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 3000:80
    app:
        image: python:3.6
        volumes: 
            # Aplicação
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh